language: python
dist: bionic
python:
  - "3.9"

stages:
  - Testing
  - Deploy

before_install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
install:
  - poetry install

jobs:
  include:
    - stage: Testing
      name: tests
      script: python3 -m unittest
    - stage: Deploy
      script: skip
      before_deploy:
        - poetry build
        - poetry config repositories.testpypi https://test.pypi.org/legacy/
        - poetry config http-basic.testpypi $TEST_PYPI_USERNAME $TEST_PYPI_PASSWORD
      deploy:
        provider: script
        script: poetry publish -r testpypi
        skip_cleanup: true
        on:
          branch: master
          python: '3.9'
          tags: true
      if: tag IS present
